### ISSUE TITLE
help for reproducing the results in the paper

### ISSUE THREAD

**Issue by zhenchuan** [linkedin/photon-ml#226]
I want to reproduce the results(KDD Cup 2012 Track 2) in the paper using photon-ml, but i failed to get the **best** result of the paper. 
can you provide the detailed training process of it?

thanks

**Comment by ashelkovnykov** [comment]
Hello,

Could you please be more specific, did you mean that you failed to get the public AUC achieved by the `G-All` model from the paper? What AUC did you achieve? What is your current training process?

Pinging @XianXing and @timyitong

**Comment by XianXing** [comment]
Thanks for your interest in this @zhenchuan, and +1 on what Alex said.

Due to the space constraint of the KDD paper, we couldn't put all details of the experiment setting there. And I wish I could be able to share the detailed shell script used to run the experiment with you, but I no longer have access to it because I left LinkedIn a few months ago.

But I still want to help here, because the experiment setting was not that complicated, and it didn't take us a long time of fine-tuning before getting the results reported in the paper. In order to further assist you on this issue, can you provide the following information?

1. Which features did you use to train the model?
2. What type of feature transformers did you apply on those features before calling GAME to train the model. For example, did you try these [features transformers](http://spark.apache.org/docs/latest/mllib-feature-extraction.html#tf-idf)? 
3. What types of random effects did you include for the G-All model, e.g., G-All = global model +per-user model + per-advertiser model + per-ad model +per-query model + per-title model + per-keyword model ?
4. For each type random effect, how did you config the features used for that random effect?
5. What was the AUC you got, for which model (e.g., G-All, G-Query, etc)? 

If you have any questions on points 1-5 listed above, please take a look at the [tutorial](https://github.com/linkedin/photon-ml/wiki/Photon-ML-Tutorial) and get a sense of how a GAME model is configured.

Or may be you can share the script that you used to config and run GAME with us, so I can take a further look.

**Comment by fastier-li** [comment]
I am going to close this issues for now, assuming it is no longer an issue. Please re-open if needed.

**Comment by zhenchuan** [comment]
sorry for the late reply. 
thanks @XianXing for your detailed explains.
i've tried the GAME model, it did well  . 

i mixed Globle & G-AD with the features of the tutorial , got the result as belows 

```
2017-03-12T17:36:18.139+0800 [INFO] Training objective function value after updating coordinate with id global-cord at iteration 0 is:
2017-03-12T17:37:17.412+0800 [INFO] Evaluation metric computed with AUC after updating coordinateId global-cord at iteration 0 is 0.6283830477084686
2017-03-12T18:07:14.601+0800 [INFO] Evaluation metric computed with AUC after updating coordinateId ad-cord at iteration 0 is 0.7228666232879889
```

**Comment by zhenchuan** [comment]
@XianXing In addition, I have a question about the `userFeatures` in the tutorial .  
it looks like features 0 to 9 .   
but the raw features of the dataset  is age|gender , how did this transform happen ?  How did I replace it with one-hot-encoding ?


```json
[
    {
        "term": "", 
        "name": "0", 
        "value": 0.6436742813579106
    }, 
    {
        "term": "", 
        "name": "1", 
        "value": -0.03708427408724602
    }, 
    {
        "term": "", 
        "name": "2", 
        "value": 0.3507769198297949
    }, 
    {
        "term": "", 
        "name": "3", 
        "value": 0.7300977754238521
    }, 
```
