### ISSUE TITLE
Using/Refactoring for Standalone Model Runs in Spark-Scala

### ISSUE THREAD

**Issue by sadatnfs** [linkedin/photon-ml#481]
Hello! I just came across photon-ml when I was searching for possible random effects modeling in Spark, and it looks like there's a lot of what I'm looking for implemented in this package! I was wondering if there are any objects to make this a standalone importable package that I can run RE models in a Spark session (REPL to test code for example) rather than using spark-submit every time?

**Comment by joshvfleming** [comment]
Hi @sadatnfs. It's somewhat involved, but you can run photon-ml in a notebook. See the tutorial here for an example: https://github.com/linkedin/photon-ml/wiki/Photon-ML-Tutorial

The API has probably changed since the time of the tutorial. Check the driver code (https://git.io/JOYa0) for current usage.

**Comment by sadatnfs** [comment]
Much appreciate it Josh! This is exactly what I was searching for, and can learn from! Thank you!
