### ISSUE TITLE
Fix all Scala style warnings

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#53]
In order to enable the Scala style check, we need to fix all the existing warnings issues reported by `./gradlew scalaStyle` first. Since most of the Scala style warnings are non-trivial to fix, several PRs will be pipelined to address them group by group.

**Comment by fastier-li** [comment]
I believe we don't have significant Scala style warnings today. I'll double check and probably close this item soon.

**Comment by fastier-li** [comment]
I did a round of cleaning up warnings recently, and the number should have gone down. However, we decided to keep some of the warnings (e.g. on `Map ->`, or on type erasure), because they were either Scala bugs fixed in further Scala releases, or the fix was too cumbersome. So I'm going to close this item for now, but please reopen it and point me to specific ones you think we could fix easily, and I'll be happy to do it. Thanks!
